version: '3.9'
services:
  mysql:
    image: mysql:latest
    env_file:
      - ./env/mysql.env
    ports:
      - $MYSQL_PORT:3306
    volumes:
      - ./vols/mysql/data/:/var/lib/mysql/
    user: $UID:$UID
  adminer:
    image: adminer:latest
    env_file:
      - ./env/adminer.env
    ports:
      - $ADMINER_PORT:8080
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - $MAILHOG_SMTP_PORT:1025
      - $MAILHOG_UI_PORT:8025
  app:
    image: $APP_IMAGE
    build:
      context: .
      dockerfile: ./Dockerfiles/app.Dockerfile
      args:
        UID: $UID
    ports:
      - 5173:5173
    volumes:
      - $APP_VOLUMES_SRC:/var/www/html/
      - ./vols/app/docker-user-home/:/home/www-data/
    env_file:
      - ./env/app.env
  static:
    image: nginx:alpine
    volumes:
      - $STATIC_VOLUMES_PUBLIC:/usr/share/nginx/html/
  proxy:
    image: $PROXY_IMAGE
    build:
      context: .
      dockerfile: ./Dockerfiles/proxy.Dockerfile
    ports:
      - $PROXY_PORT:80
    env_file:
      - ./env/proxy.env
